CREATE TABLE LIBRARY(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name varchar(50) NOT NULL,
address varchar(100) NOT NULL,
zipcode varchar(6) NOT NULL);

CREATE TABLE CATEGORY(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
library_id BIGINT NOT NULL,
name varchar(50) NOT NULL);

ALTER TABLE CATEGORY
ADD CONSTRAINT category_library_id
FOREIGN KEY (library_id) REFERENCES LIBRARY(id);

CREATE TABLE BOOK(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
category_id BIGINT NOT NULL,
name varchar(200) NOT NULL,
author varchar(100) NOT NULL,
rate TINYINT NULL);

ALTER TABLE BOOK
ADD CONSTRAINT book_category_id
FOREIGN KEY (category_id) REFERENCES CATEGORY(id);
